name: Build Manuscript (Zotero → .bib → Quarto PDF)

on:
  workflow_dispatch:
  push:
    paths:
      - 'manuscript/**'
      - 'renv.lock'
      - '.github/workflows/build-manuscript.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Your specific group & collection from the URL you shared
      ZOTERO_GROUP_ID: "5979835"
      ZOTERO_COLLECTION_KEY: "HY6TKCRU"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Fetch + Convert (Zotero → CSL-JSON → BibTeX) ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build extra/references.bib from Zotero
        env:
          API_KEY: ${{ secrets.ZOTERO_API_KEY }}
          GROUP_ID: ${{ env.ZOTERO_GROUP_ID }}
          COLL_KEY: ${{ env.ZOTERO_COLLECTION_KEY }}
        run: node .github/scripts/fetch_group_bibtex_with_pinned.mjs

      # ---------- R + renv ----------
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2
        with:
          # Defaults to renv.lock at repo root; adjust if yours lives elsewhere
          cache-version: 1

      # ---------- Quarto + TinyTeX ----------
      - name: Setup Quarto (with TinyTeX for PDF)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      # If your document requires extra LaTeX packages not auto-installed,
      # you can add a step here to install them with tlmgr, e.g.:
      # - name: Install extra LaTeX packages
      #   run: tlmgr install <packagename>

      # ---------- Render ----------
      - name: Render manuscript to PDF
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: manuscript/manuscript.qmd
          # By default renders formats declared in the doc.
          # Ensure manuscript.qmd lists 'pdf' (or has default-format: pdf in _quarto.yml)

      # ---------- Upload artifact ----------
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: manuscript-pdf
          path: manuscript/manuscript.pdf
          if-no-files-found: error
